---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::qcat=1.1.0
  - conda-forge::python=3.7.3
  - conda-forge::setuptools=41.0
