---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::blast=2.14.0
  - bioconda::diamond=2.1.8
  - bioconda::proteinortho=6.3.0
