---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::genometools-genometools=1.6.5
  - bioconda::ltr_harvest_parallel=1.1
  - conda-forge::python=3.10.13
  - conda-forge::setuptools=69.1
