---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::quantms-utils=0.0.23
  - bioconda::sdrf-pipelines=0.0.32
  - conda-forge::python=3.13.3
  - conda-forge::setuptools=80.1
