---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pychopper=2.7.10
  - conda-forge::python=3.12.4
  - conda-forge::setuptools=71.0
  - conda-forge::pandas=2.2
